Floppi-Music: floppi.drive.MusicalFloppy Class Reference
floppi.drive.MusicalFloppy Class Reference
Class for controlling one musical floppy drive.
Public Member Functions
def __init__
Constructor.
def run
Run the drive thread.
def stop
Stop this thread (set the exit flag).
def tracks
Move the floppy head a certain number of tracks.
def home
Move to home position, which is the middle track.
def vibrate
Shake the head with a certain interval.
def tone
Play a certain frequency, for duration seconds.
def play
Add a tone to the play queue.
Public Attributes
wakeup
An event used by the engine to wake the thread up.
Private Attributes
_gpio
Holds reference to the GPIO object in use.
_pin_direction
Holds the native pin number of the GPIO pin connected to the DIRECTION pin of the floppy interface.
_pin_step
Holds the native pin number of the GPIO pin connected to the STEP pin of the floppy interface.
_playqueue
Queue of tones to play, containing tuples of (frequency, duration)
_exit
Exit flag for the thread.
_engine
Reference to the FloppyMusicEngine.
Detailed Description
Class for controlling one musical floppy drive.
This class controls one floppy drive in its own thread, so several drives can be used in parallel.
Definition at line 34 of file drive.py.
Constructor & Destructor Documentation
def floppi.drive.MusicalFloppy.__init__ (self, gpio, pins, engine)
Constructor.
Set up the drive thread.
Parameters
self the object pointer
gpio reference to the GPIO object in use
pins A tuple defining the pair of (direction, step) pins
Definition at line 65 of file drive.py.
     def __init__(self, gpio, pins, engine):
         Thread.__init__(self)
         # Store attributes
         self._gpio = gpio
         self._pin_direction = pins[0]
         self._pin_step = pins[1]
         self._playqueue = []
         self._exit = False
         self._engine = engine
         self.wakeup = Event()
Member Function Documentation
def floppi.drive.MusicalFloppy.home (self)
Move to home position, which is the middle track.
This method moves the head to the home position. Currently, this is the middle track (40), but this may change as we advance the floppy music quality.
Parameters
self the object pointer
Definition at line 127 of file drive.py.
References floppi.drive.MusicalFloppy._pin_direction, and floppi.drive.MusicalFloppy.tracks().
Referenced by floppi.drive.MusicalFloppy.run().
     def home(self):
         # Move 80 tracks, just to be sure
         self.tracks(80)
         # Toggle direction
         self._gpio.toggle(self._pin_direction)
         # Move 40 tracks back
         self.tracks(40)
def floppi.drive.MusicalFloppy.play (self, tone)
Add a tone to the play queue.
This method adds a tone to the _playqueue, so the main loop will pick it up and play it.
Parameters
self the object pointer
tone a tuple of (frequency, duration)
Definition at line 178 of file drive.py.
     def play(self, tone):
         if type(tone) is list:
             self._playqueue.extend(tone)
         else:
             self._playqueue.append(tone)
def floppi.drive.MusicalFloppy.run (self)
Run the drive thread.
Main loop function for the drive thread. It will set up the drive, then start playing tones from the _playqueue list.
Parameters
self the object pointer
Definition at line 83 of file drive.py.
References floppi.drive.MusicalFloppy._exit, floppi.drive.MusicalFloppy._pin_direction, floppi.drive.MusicalFloppy._pin_step, floppi.drive.MusicalFloppy._playqueue, floppi.drive.MusicalFloppy.home(), and floppi.drive.MusicalFloppy.tone().
     def run(self):
         # Explicitly set pins high
         self._gpio.high(self._pin_direction)
         self._gpio.high(self._pin_step)
         # Go to home position, which is the middle track
         self.home()
         while not self._exit:
             if self._playqueue:
                 tone = self._playqueue.pop(0)
                 if tone == 1:
                     self._engine.syncmark(self)
                     self.wakeup.wait()
                     self.wakeup.clear()
                 else:
                     self.tone(tone[0], tone[1])
             else:
                 self._engine.finished(self)
                 break
def floppi.drive.MusicalFloppy.stop (self)
Stop this thread (set the exit flag).
Parameters
self the object pointer
Definition at line 107 of file drive.py.
References floppi.drive.MusicalFloppy._exit.
     def stop(self):
         self._exit = True
def floppi.drive.MusicalFloppy.tone (self, freq, duration)
Play a certain frequency, for duration seconds.
This method wraps the vibrate method with another form of arguments, more convenient for playing notes.
Parameters
self the object pointer
freq the frequency of the desired tone, in Hertz
duration duration of the tone, in seconds
Definition at line 162 of file drive.py.
References floppi.drive.MusicalFloppy.vibrate().
Referenced by floppi.drive.MusicalFloppy.run().
     def tone(self, freq, duration):
         if duration == 0:
             return
         if freq == 0:
             sleep(duration)
         else:
             self.vibrate(1.0/freq, int(freq*duration), duration-int(freq*duration)/freq)
def floppi.drive.MusicalFloppy.tracks (self, count)
Move the floppy head a certain number of tracks.
Parameters
self the object pointer
count the number of tracks to move
Definition at line 114 of file drive.py.
References floppi.drive.MusicalFloppy._pin_step.
Referenced by floppi.drive.MusicalFloppy.home().
     def tracks(self, count):
         for i in range(count):
             self._gpio.toggle(self._pin_step)
             sleep(.002)
             self._gpio.toggle(self._pin_step)
def floppi.drive.MusicalFloppy.vibrate (self, interval, count, rest)
Shake the head with a certain interval.
Moves the head back and forth some times, pausing in between. You can make sounds at certain frequencies by setting the interval to 1/freq. Adjust the duration of the vibration by setting the count to freq*duration.
Parameters
self the object pointer
interval the pause between movements, in seconds
count how often to move the head
rest how long to wait to compensate rounding problems
Definition at line 146 of file drive.py.
References floppi.drive.MusicalFloppy._pin_direction, and floppi.drive.MusicalFloppy._pin_step.
Referenced by floppi.drive.MusicalFloppy.tone().
     def vibrate(self, interval, count, rest):
         for i in range(count):
             self._gpio.toggle(self._pin_step)
             sleep(interval)
             self._gpio.toggle(self._pin_step)
             self._gpio.toggle(self._pin_direction)
         sleep(rest)
Member Data Documentation
floppi.drive.MusicalFloppy._engine private
Reference to the FloppyMusicEngine.
Definition at line 74 of file drive.py.
floppi.drive.MusicalFloppy._exit private
Exit flag for the thread.
Definition at line 73 of file drive.py.
Referenced by floppi.drive.MusicalFloppy.run(), floppi.drive.MusicalFloppyEngine.run(), floppi.drive.MusicalFloppy.stop(), and floppi.drive.MusicalFloppyEngine.stop().
floppi.drive.MusicalFloppy._gpio private
Holds reference to the GPIO object in use.
Definition at line 69 of file drive.py.
floppi.drive.MusicalFloppy._pin_direction private
Holds the native pin number of the GPIO pin connected to the DIRECTION pin of the floppy interface.
Definition at line 70 of file drive.py.
Referenced by floppi.drive.MusicalFloppy.home(), floppi.drive.MusicalFloppy.run(), and floppi.drive.MusicalFloppy.vibrate().
floppi.drive.MusicalFloppy._pin_step private
Holds the native pin number of the GPIO pin connected to the STEP pin of the floppy interface.
Definition at line 71 of file drive.py.
Referenced by floppi.drive.MusicalFloppy.run(), floppi.drive.MusicalFloppy.tracks(), and floppi.drive.MusicalFloppy.vibrate().
floppi.drive.MusicalFloppy._playqueue private
Queue of tones to play, containing tuples of (frequency, duration)
Definition at line 72 of file drive.py.
Referenced by floppi.drive.MusicalFloppy.run(), and floppi.drive.MusicalFloppyEngine.run().
floppi.drive.MusicalFloppy.wakeup
An event used by the engine to wake the thread up.
Definition at line 75 of file drive.py.
The documentation for this class was generated from the following file:
src/floppi/drive.py