Floppi-Music: floppi.rpi.GPIO Class Reference
floppi.rpi.GPIO Class Reference
GPIO class, reduced to what we need for Floppi-Music.
Public Member Functions
def __init__
Constructor.
def high
Set a selected pin high, by native board pin number.
def low
Set a selected pin low, by native board pin number.
def toggle
Set a selected pin low if it was high, and high if it was low.
Static Private Member Functions
def _gpio_bench
GPIO benchmark function to pass to timeit.
Private Attributes
_gpiodelay
Measured delay for GPIO toggling.
Static Private Attributes
tuple _gpios = (3, 5, 7, 8, 10, 11, 12, 13, 15, 16, 18, 19, 21, 22, 23, 24, 26)
All pins that are GPIO pins.
Detailed Description
GPIO class, reduced to what we need for Floppi-Music.
Definition at line 34 of file rpi.py.
Constructor & Destructor Documentation
def floppi.rpi.GPIO.__init__ (self)
Constructor.
Initializes the whole GPIO header as output.
Parameters
self the object pointer
Definition at line 61 of file rpi.py.
     def __init__(self):
         # Run GPIO benchmark
         self._gpiodelay = timeit('gpio_bench()', 'from floppi.rpi import GPIO; gpio_bench = GPIO._gpio_bench()', number=100000) / 100000
         # Set GPIO mode to native Broadcom
         _GPIO.setmode(_GPIO.BOARD)
         # Setup all pins as output
         for pin in self._gpios:
             _GPIO.setup(pin, _GPIO.OUT)
Member Function Documentation
def floppi.rpi.GPIO._gpio_bench () static private
GPIO benchmark function to pass to timeit.
Returns
a reference to the real benchmark function for timeit
Definition at line 46 of file rpi.py.
     def _gpio_bench():
         _GPIO.setmode(_GPIO.BOARD)
         _GPIO.setwarnings(False)
         _GPIO.setup(3, _GPIO.OUT)
         def _gpio_bench_do():
             _GPIO.output(3, not _GPIO.input(3))
         return _gpio_bench_do
def floppi.rpi.GPIO.high (self, pin)
Set a selected pin high, by native board pin number.
Parameters
self the object pointer
pin the native number of the pin to set
Exceptions
NoSuchGPIO if the selected pin is not a GPIO pin
Definition at line 78 of file rpi.py.
References floppi.rpi.GPIO._gpios.
     def high(self, pin):
         if pin in self._gpios:
             _GPIO.output(pin, _GPIO.HIGH)
         else:
             raise NoSuchGPIO("Pin %d is not a GPIO pin." % pin)
def floppi.rpi.GPIO.low (self, pin)
Set a selected pin low, by native board pin number.
Parameters
self the object pointer
pin the native number of the pin to set
Exceptions
NoSuchGPIO if the selected pin is not a GPIO pin
Definition at line 90 of file rpi.py.
References floppi.rpi.GPIO._gpios.
     def low(self, pin):
         if pin in self._gpios:
             _GPIO.output(pin, _GPIO.LOW)
         else:
             raise NoSuchGPIO("Pin %d is not a GPIO pin." % pin)
def floppi.rpi.GPIO.toggle (self, pin)
Set a selected pin low if it was high, and high if it was low.
This method looks at the reported state of the pin.
Parameters
self the object pointer
pin the native number of the pin to set
Exceptions
NoSuchGPIO if the selected pin is not a GPIO pin
Definition at line 104 of file rpi.py.
References floppi.rpi.GPIO._gpios.
     def toggle(self, pin):
         if pin in self._gpios:
             _GPIO.output(pin, not _GPIO.input(pin))
         else:
             raise NoSuchGPIO("Pin %d is not a GPIO pin." % pin)
Member Data Documentation
floppi.rpi.GPIO._gpiodelay private
Measured delay for GPIO toggling.
Definition at line 63 of file rpi.py.
floppi.rpi.GPIO._gpios = (3, 5, 7, 8, 10, 11, 12, 13, 15, 16, 18, 19, 21, 22, 23, 24, 26) static private
All pins that are GPIO pins.
Definition at line 37 of file rpi.py.
Referenced by floppi.rpi.GPIO.high(), floppi.rpi.GPIO.low(), and floppi.rpi.GPIO.toggle().
The documentation for this class was generated from the following file:
src/floppi/rpi.py