from floppi.drive import MusicalFloppyEngine
from floppi.rpi import GPIO
from floppi.music import mml

e = MusicalFloppyEngine(GPIO(), [(3,5),(11,13),(15,19),(21,23)])
e.start()

#           1        2      3           4         5          6           7               8           9                10                11                                 12                        13                               14                         15                               16                         17                    18                         19                                                                           20                                                           21                                                                        22                                                                     23                                                                        24                                                                    25                                                                       26                                                                     27                              28
a = mml("t84 p1      | p1   | f+edc+o3  | babo4c+ | dc+o3ba  | gf+ge     | o4do3abf+     | gdga      | >dabf+          | gdga            | l16o4dc+do3dc+aef+do4dc+<bc+f+ab | gf+egf+edc+o3bagf+egf+e | def+gaeagf+bagagf+e            | d<bbo4c+dc+o3bagf+ebabag | l8f+o4f+e4p8df+4               | l4babo5c+                | l8do4dl4c+p8<b8d    | d.l8ddgda                | l16amlf+32g32mnamll32f+gmnamlo3abo4c+def+gmnf+16mldemnf+16mlo3f+gabagaf+ga | mng16mlbag16f+ef+edef+gabmng16mlbamnb16o4c+do3abo4c+def+ga | mnf+16mldemnf+16mledec+def+edc+mnd16ml<bc+mnd16o3mldef+gf+emnf+o4mldc+d | mn<b16mldc+o3mnb16mlagagf+gabo4c+dmn<b16mldc+mnd16mlc+<bc+dedc+d<bc+ | l8mndpc+p<bpdp                                                          | o3dpdpdpep                                                          | l4>dabf+                                                               | gdga                                                                 | >dabf+                        | gdga        ")
b = mml("t84 do3abf+ | gdga | o4do3abf+ | gdp2    | o4f+edc+ | o3babo4c+ | dc+o3ba       | gf+ge     | l8df+agf+df+e   | d<bdagbag       | f+deo4c+df+ao3a                  | bgaf+do4dd.c+16         | l16dc+do3dc+aef+do4dc+<bc+f+ab | gf+egf+edc+o3bagf+egf+e  | def+gaeagf+bagagf+e            | d<bbo4c+dc+o3bagf+ebabag | f+8o4f+8ep8d8f+     | babo5c+                  | d8o4d8c+p8<b8d                                                             | d.l8ddgda                                                  | d16mll32f+gmna16mlf+gmnao3mlabo4c+def+gmnf+16mldemnf+16o3mlf+gabagaf+ga | mng16mlbamng16mlf+ef+edef+gabmng16mlbamnb16ml>c+d+mnamlbo4c+def+ga   | mnf+16mldemnf+16mledec+def+edc+mnd16ml<bc+mnd16o3mldef+gf+edmneo4mldc+d | mn<b16mldc+mno3b16mlagagf+gabo4c+dmn<b16mldcmnd16mlc+<bc+dedc+d<bc+ | l8mndpc+p<b+dp                                                         | dpdpdpep                                                             | papapf+pa                     | pgpf+pgp>e        ")
c = mml("t84 do3abf+ | gdga | o4do3abf+ | gdga    | >dabf+   | gdp2      | o4f+edc+      | o3babo4c+ | dc+o3ba         | gf+ge           | l8df+agf+df+e                    | d<bdagbag               | f+deo4c+df+ao3a                | bgaf+do4dd.c+16          | l16dc+do3dc+aef+do4dc+<bc+f+ab | gf+egf+edc+o3bagf+egf+e  | def+gaeagf+bagagf+e | d<bbo4c+dc+o3bagf+ebabag | l4f+8o4f+8ep8d8f+                                                          | babo5c+                                                    | d8o4d8cp8<b8d                                                           | d.l8ddgea                                                            | l32a16mlf+gmna16mlf+gmnaml<a<bc+def+gmnf+16mldemnf+16o3mlf+gabagaf+ga   | mng16mlbamngmlf+ef+edef+gabmng16mlbamnb16mlo4c+dmn<aml<bc+def+ga    | mnf16mldemnf+16mledec+def+edc+mnd16ml<bc+mnd16o3mldef+gf+emnf+mlo4dc+d | mn<b16mldc+mno3b16mlagagf+gabo4c+dmn<b16mldc+mnd16mlc+<bc+dedc+d<bc+ | l8mndpc+p<bpdp                | o3dpdpdpep        ")
d = mml("t84 do3abf+ | gdga | o4do3abf+ | gdga    | >dabf+   | gdga      | l8df+agf+df+e | d<bdagbag | f+deo4c+df+ao3a | bgaf+do4dd.c+16 | l4do3abf+                        | gdga                    | >dabf+                         | gdga                     | >dabf+                         | gdga                     | >dabf+              | gdga                     | >dabf+                                                                     | gdga                                                       | >dabf+                                                                  | gdga                                                                 | >dabf+                                                                  | gdga                                                                | l8papapf+pa                                                            | pgpf+pgp>e                                                           | l16>f+f+gf+eo4ef+edo3f+dbaaga | bb>c+baagabbabo4c+c+<bc+        ")

e.play([a,b,c,d])
